volumes:
  mysql_data:

services:
  db:
    image: mysql:lts
    environment:
      MYSQL_ROOT_PASSWORD: password"
    ports: "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./backend:/rails_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    ty: true
    stdin_open: true
